### ISSUE TITLE
Repository Layout with respect to Graal/Truffle

### ISSUE THREAD

**Issue by smarr** [SOM-st/black-diamonds#2]
One of the big questions, where I don't have yet a favorite answer is: how to structure the repositories, and dependencies on Truffle.

The two options I see are:

1. Have BlackDiamonds depend directly on Truffle, and make languages depend on the Truffle of BlackDiamonds, too.

2. Have BlackDiamonds only weekly depend on Truffle by configuring it so it finds an existing Truffle, and enables languages to update Truffle freely.

Both options have issues, because we likely won't have tested BlackDiamonds with an arbitrary Truffle version. So, updating Truffle independently can lead to issues.
On the other hand, when we bind BlackDiamonds to a Truffle version, we always need to update BlackDiamonds, and the reverse, update the language every time we update BlackDiamonds and it includes an update Truffle.

So, we got either the option of:

1. language
   -> black-diamonds -> truffle

2. language
  -> truffle
  -> black-diamonds

Any preferences, remarks, suggestions?
@richard-roberts @charig

**Comment by charig** [comment]
It is true that both alternatives have strong cons. That said, I'd go for 2. My main point is that it will still be necessary for some "advanced" language developers to have a customized truffle. For instance for using like me some special features for the reflective compiler, or like you needed Stefan for the dym/debugger tools. In that cases, if using alternative 1 developers would have to fork black diamonds just to use their special truffle version which in my opinion would not be desirable. My 2 cents...

**Comment by smarr** [comment]
Ok, then let's go with option 2.

This means, CI needs to be able to download the Graal+Truffle repo for testing.
Or use a configured path, in case it is always available.

For languages, I'll assume that BD will just be integrated in an existing setup, which already provides Truffle/Graal on the classpath.

**Comment by smarr** [comment]
The second option was implemented in a first version with #3.
